import type { Metadata } from "next";
import "./globals.css"

export const metadata: Metadata = {
  title: "陈鑫磊的博客",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-CN">
      <body>
        {children}
      </body>
    </html>
  );
}
